/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00210d",
        "inverse-primary": "#75db94",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#40000f",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#0d1c2e",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "primary-fixed": "#91f8ae",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "on-secondary-container": "#57657a",
        "tertiary-fixed": "#ffdadb",
        "primary-container": "#108548",
        "on-tertiary-fixed-variant": "#812535",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "on-error-container": "#93000a",
        "secondary-container": "#d5e3fc",
        "surface-tint": "#006d39",
        "tertiary-container": "#bb515f",
        "on-tertiary-container": "#fffaf9",
        "secondary-fixed-dim": "#b9c7df",
        "surface-container-high": "#e6e8ea",
        "secondary": "#515f74",
        "tertiary": "#9c3948",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#005229",
        "outline": "#6e7a6f",
        "on-primary-container": "#f1fff0",
        "tertiary-fixed-dim": "#ffb2b8",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3a485b",
        "on-error": "#ffffff",
        "on-surface-variant": "#3e4a40",
        "primary": "#006a37",
        "outline-variant": "#becabd",
        "primary-fixed-dim": "#75db94"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
